name: Terraform Lint
on:
  push:
    branches: [main]

jobs:
  tflint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        name: Checkout source code

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v1
        name: Setup tflint
        with:
          tflint_version: v0.36.2

      - name: Show version
        run: tflint --version

      - name: Init tflint
        run: tflint --init

      - name: Run TFtflintLint
        run: tflint -f compact
